--QUERING OUR DATABASE

--Query 1: Para cada persona que administre más de una empresa, listar el nombre y fecha de nacimiento

SELECT P.NOMBRE, P.FECHA_NAC
FROM PERSONA P, EMPRESA E, ADMINISTRA A
WHERE A.CIF = E.CIF AND A.DNI = P.DNI
GROUP BY P.NOMBRE, P.FECHA_NAC
HAVING COUNT(*) > 1;

--Query 2: Listar el id y la deuda pendiente de los clientes cuya nota sea inferior a 5. Ordenar la consulta descendentemente por deuda pendiente.

SELECT C.IDCLIENTE, A.DEUDA_PEND
FROM CLIENTE C, CALIFICACION A
WHERE A.IDCLIENTE = C.IDCLIENTE AND A.NOTA < 5
ORDER BY A.DEUDA_PEND DESC;

--Query 3: Listar los clientes que no tienen mecanismos de nivel 2, identificando el tipo de cliente (persona/empresa)

SELECT DNI IDENTIFICADOR, NOMBRE, 'PERSONA' TIPO_CLIENTE
FROM PERSONA
WHERE IDCLIENTEP NOT IN ( --Clientes con mecanismo TIENE
SELECT DISTINCT T.IDCLIENTE
FROM TIENE T JOIN MEC_TIENE MT ON T.NOMBREMEC = MT.NOMBREMEC
UNION
--Clientes con mecanismo ES
SELECT DISTINCT T.IDCLIENTE
FROM TIENE T JOIN MEC_ES ME ON T.NOMBREMEC = ME.NOMBREMEC)
UNION
SELECT CIF IDENTIFICADOR, NOMBRE, 'EMPRESA' TIPO_CLIENTE
FROM EMPRESA
WHERE IDCLIENTEE NOT IN (--Clientes con mecanismo TIENE
SELECT DISTINCT T.IDCLIENTE
FROM TIENE T JOIN MEC_TIENE MT ON T.NOMBREMEC = MT.NOMBREMEC
UNION
--Clientes con mecanismo ES
SELECT DISTINCT T.IDCLIENTE
FROM TIENE T JOIN MEC_ES ME ON T.NOMBREMEC = ME.NOMBREMEC);

--Query 4: Cantidad de operaciones del tipo “TRANSFERENCIA” validadas por mecanismos de autenticación y ordenadas de forma descendente.

SELECT NOMBRENV2 "NOMBRE MECANISMO", COUNT(*) AS "CANTIDAD TRANSFERENCIAS"
FROM OPERACION
WHERE UPPER(TIPO_OP) = 'TRANSFERENCIA'
GROUP BY NOMBRENV2, TIPO_OP
ORDER BY 2 DESC;

--Query 5: Listar las parejas de miembros de la misma unidad familiar.

SELECT P1.NOMBRE, P2.NOMBRE
FROM PERSONA P1, PERSONA P2
WHERE P1.DNI < P2.DNI AND P1.CALLE = P2.CALLE AND P1.NUMERO = P2.NUMERO;

--Query 6: Relación de empresas administradas por miembros de la misma unidad familiar
 
SELECT E.CIF, E.NOMBRE
FROM EMPRESA E, ADMINISTRA A1, ADMINISTRA A2
WHERE E.CIF = A1.CIF AND A1.CIF = A2.CIF AND A1.DNI < A2.DNI AND (A1.DNI, A2.DNI) IN(
    SELECT P1.DNI, P2.DNI
    FROM PERSONA P1, PERSONA P2
    WHERE P1.DNI < P2.DNI AND P1.CALLE = P2.CALLE AND P1.NUMERO = P2.NUMERO);

--Query 7: Tipo de canal más utilizado (en cantidad de operaciones realizadas) para cada tipo de cliente:

SELECT 'PERSONA' TIPO_CLIENTE, A.TIPOCANAL, B.CANTIDAD  
FROM (SELECT TIPOCANAL, COUNT(*) AS CANTIDAD
FROM (SELECT CASE WHEN TIPOCANAL LIKE 'WEB%' THEN 'BANCO_WEB'
WHEN TIPOCANAL LIKE 'ATM%' THEN 'ATM'
WHEN TIPOCANAL LIKE 'APP%' THEN 'APP'
ELSE''END TIPOCANAL
FROM OPERACION
WHERE IDCLIENTE IN (SELECT IDCLIENTEP FROM PERSONA))
GROUP BY TIPOCANAL) A 
JOIN (SELECT MAX(CANTIDAD) CANTIDAD
FROM (SELECT TIPOCANAL, COUNT(*) CANTIDAD
FROM (SELECT CASE WHEN TIPOCANAL LIKE 'WEB%' THEN 'BANCO_WEB'
WHEN TIPOCANAL LIKE 'ATM%' THEN 'ATM'
WHEN TIPOCANAL LIKE 'APP%' THEN 'APP'
ELSE''END TIPOCANAL
FROM OPERACION
WHERE IDCLIENTE IN (SELECT IDCLIENTEP FROM PERSONA))
GROUP BY TIPOCANAL)) B ON A.CANTIDAD = B.CANTIDAD
UNION
SELECT 'EMPRESA' AS TIPO_CLIENTE, A.TIPOCANAL, B.CANTIDAD  
FROM (SELECT TIPOCANAL, COUNT(*) CANTIDAD
FROM (SELECT CASE WHEN TIPOCANAL LIKE 'WEB%' THEN 'BANCO_WEB'
WHEN TIPOCANAL LIKE 'ATM%' THEN 'ATM'
WHEN TIPOCANAL LIKE 'APP%' THEN 'APP'
ELSE''END TIPOCANAL
FROM OPERACION
WHERE IDCLIENTE IN (SELECT IDCLIENTEE FROM EMPRESA))
GROUP BY TIPOCANAL) A 
JOIN (SELECT MAX(CANTIDAD) CANTIDAD
FROM (SELECT TIPOCANAL, COUNT(*) CANTIDAD
FROM (SELECT CASE WHEN TIPOCANAL LIKE 'WEB%' THEN 'BANCO_WEB'
WHEN TIPOCANAL LIKE 'ATM%' THEN 'ATM'
WHEN TIPOCANAL LIKE 'APP%' THEN 'APP'
ELSE''END AS TIPOCANAL
FROM OPERACION
WHERE IDCLIENTE IN (SELECT IDCLIENTEE FROM EMPRESA))
GROUP BY TIPOCANAL)) B ON A.CANTIDAD = B.CANTIDAD;

--Query 8: Listar el número de ATM por cada zona, ordenado por cantidad de forma descendente 

SELECT DISTINCT PROVINCIA, COUNT (DISTINCT A.IDCAJERO) AS "CANTIDAD ATM"
FROM ATM A JOIN ZONA Z ON A.CPRO = Z.CPRO
GROUP BY PROVINCIA
ORDER BY 2 DESC;

--Query 9: Cantidad de bloqueos por mecanismos de autenticación realizados por clientes del tipo Persona. 

SELECT NOMBREMEC, COUNT(*) AS "Nº DE BLOQUEOS"
FROM ABM_CLIENTES 
WHERE UPPER(OPERACION) = 'BLOQUEO' AND IDCLIENTE IN (
    SELECT IDCLIENTEP FROM PERSONA)
    GROUP BY NOMBREMEC
    ORDER BY 2 DESC;

--Query 10: Cantidad de operaciones realizadas por cada persona, clasificada por tipo, año y mecanismo utilizado. 

SELECT P.NOMBRE, O.TIPO_OP, EXTRACT(YEAR FROM O.FECHA) AÑO, MECS.NOMBREMEC, COUNT(*) CANTIDAD
FROM PERSONA P JOIN OPERACION O ON P.IDCLIENTEP = O.IDCLIENTE
JOIN (SELECT NOMBREMEC, NOMBREMECNV2 FROM MEC_TIENE UNION SELECT NOMBREMEC, NOMBREMECNV2 FROM MEC_ES) MECS ON O.NOMBRENV2 = MECS.NOMBREMECNV2
GROUP BY P.NOMBRE, O.TIPO_OP, EXTRACT(YEAR FROM O.FECHA), MECS.NOMBREMEC
ORDER BY 3 DESC;